#include "i2c_hal.h"
#include "stm32f4xx_hal.h"

// hi2c1 is generated by CubeMX. I2C1 on PB8 (SCL) / PB9 (SDA) 
extern I2C_HandleTypeDef hi2c1;

#define I2C_TIMEOUT_MS  10

void i2c_hal_init(void)
{
    // Init is done by MX_I2C1_Init() called from CubeMX main 
}

I2C_Status_t i2c_write_reg(uint8_t dev_addr, uint8_t reg, const uint8_t *data, size_t len){
    HAL_StatusTypeDef s = HAL_I2C_Mem_Write(&hi2c1, (uint16_t)(dev_addr << 1), reg, I2C_MEMADD_SIZE_8BIT, (uint8_t *)data, len, I2C_TIMEOUT_MS);
    if (s == HAL_TIMEOUT){
        return I2C_ERR_TIMEOUT;
    }
    if (s == HAL_ERROR){
        return I2C_ERR_NACK;
    }
    if (s != HAL_OK){
        return I2C_ERR_BUS;
    }
    return I2C_OK;
}

I2C_Status_t i2c_read_reg(uint8_t dev_addr, uint8_t reg, uint8_t *data, size_t len){
    HAL_StatusTypeDef s = HAL_I2C_Mem_Read(&hi2c1, (uint16_t)(dev_addr << 1), reg, I2C_MEMADD_SIZE_8BIT,  data, len, I2C_TIMEOUT_MS);
    if (s == HAL_TIMEOUT){
        return I2C_ERR_TIMEOUT;
    }
    if (s == HAL_ERROR){
        return I2C_ERR_NACK;
    }
    if (s != HAL_OK){
        return I2C_ERR_BUS;
    }
    return I2C_OK;
}
