#include "uart_hal.h"
#include "sensor_hub.h"
#include "stm32f4xx_hal.h"
#include "FreeRTOS.h"
#include "semphr.h"

// huart2 is generated by CubeMX. USART2 on PA2 (TX) / PA3 (RX).
// Maps to the ST-Link virtual COM port. 
extern UART_HandleTypeDef huart2;

void uart_hal_init(void)
{
    // Init is done by MX_USART2_UART_Init() called from CubeMX main
}

void uart_dma_transmit(const uint8_t *data, size_t len)
{
    HAL_UART_Transmit_DMA(&huart2, (uint8_t *)data, (uint16_t)len);
}

// Called by the HAL from DMA1_Stream6_IRQHandler (USART2 TX channel). 
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance != USART2){
        return;
    }

    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    xSemaphoreGiveFromISR(xTxDoneSem, &xHigherPriorityTaskWoken);
    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}
